### ISSUE TITLE
Why libgcc_s in libgfortran?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/libgfortran-feedstock#12]
I thought `libgcc` from defaults was supposed to include the gcc runtime libraries and `libgfortran` includes only `libgfortran` libraries.

**Comment by jakirkham** [comment]
As you may note, this is a Mac only package. On Mac, if we run `otool -L libgfortran.3.dylib`, then we find a number of linkages to the `libgfortran.3.dylib` library including one to `libgcc_s.1.dylib` in the environment. If we try to remove that library, then any Fortran linked libraries will crash on Mac. For example, we [can't import `numpy`]( https://github.com/conda-forge/staged-recipes/pull/1022#issuecomment-232213447 ). So we have to include `libgcc_s.1.dylib`.

There have been other attempts to split up `libgcc` into smaller libraries, but it is not so trivial to do. Please see the history in PR ( https://github.com/conda-forge/staged-recipes/pull/855 ), PR ( https://github.com/conda-forge/staged-recipes/pull/861 ), and PR ( https://github.com/conda-forge/staged-recipes/pull/1022 ). The last one is where this package came from.

**Comment by isuruf** [comment]
Thanks for the links. I'll have a look
