### ISSUE TITLE
Why only OSX?

### ISSUE THREAD

**Issue by marscher** [conda-forge/libgfortran-feedstock#9]
If one disables the defaults channel (I guess this is currently unsupported), one can not install scipy because of the lack of this package. I see that the recipe is highly adapted to OSX, but it would be desirable to have it also on the other platforms as well.

**Comment by lexual** [comment]
I too am interested in this question.
I may take a look at what is involved in making it available for Linux if I get a chance.

**Comment by lexual** [comment]
I'm going to have a crack at adding Linux support ;)

**Comment by marscher** [comment]
On 08.03.2017 01:23, lexual wrote:
> I'm going to have a crack at adding Linux support ;)
cool, good luck :)

**Comment by ocefpaf** [comment]
Now that we are vendorizing this for Linux we do have it available there too.
Closing this.
